version: "3"
services:
    redis:
      image: redis
      ports:
      - "6379"
      networks:
      - app

    deliver:
      build: ./app/go_app
      ports:
      - "8080:8080"
      networks:
      - app
      depends_on:
      - redis
      - consumer

    consumer:
      build: ./app/php_app
      ports:
      - "8000:80"
      networks:
      - app
      depends_on:
      - redis

networks:
  app: {}
