version: "2"
services:
    redis:
      image: redis
      ports:
          - "6379"
      command: redis-server

    consumer:
      build: ./app/php_app
      ports:
        - "8000:8000"
      depends_on:
          - redis

    deliver:
      build: ./app/go_app
      ports:
        - "8080:8080"
      depends_on:
          - redis
          - consumer
